version: "3.8"

services:
  db:
    image: postgres
    restart: always
    container_name: db
    environment:
      POSTGRES_PASSWORD: xenon@123
      POSTGRES_USER: mohit@xs.com
      POSTGRES_DB: database
    ports:
      - "5433:5433"
    networks:
      - notejam
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    image: imohitbhatt/notejam:4.1
    container_name: web
    command: bash -c "python2 ./notejam/manage.py syncdb --noinput && python2 ./notejam/manage.py migrate && python2 ./notejam/manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    networks:
      - notejam
    depends_on:
      - db

networks:
  notejam:

volumes:
  db-data:
